// <auto-generated />
namespace HouseKeeper2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SeedServicesTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedServicesTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201711040652524_SeedServicesTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
